import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Constraint naming convention for all ORM-declared constraints.
#
# The templates deliberately reproduce PostgreSQL's server-default names
# (<table>_<col>_fkey, <table>_pkey, <table>_<col>_key, ix_<t>_<c>) so that
# constraints generated WITHOUT an explicit name get exactly the name the
# database server would have assigned anyway. This keeps alembic autogenerate
# diff-clean against existing databases whose unnamed constraints were
# auto-named by the server, and guarantees every future autogenerated
# migration emits named constraints (so downgrade can always
# op.drop_constraint by name — see the outbox_events FK fix in 8421f73f77d9).
#
# Rules for contributors:
#   - Composite constraints (UniqueConstraint/FK over several columns) must
#     still pass an explicit name; the convention then never applies.
#   - CheckConstraint requires an explicit name: the ck template references
#     %(constraint_name)s, so an anonymous check constraint fails at DDL
#     compile time instead of shipping nameless.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "%(table_name)s_%(column_0_name)s_key",
    "ck": "%(table_name)s_%(constraint_name)s_check",
    "fk": "%(table_name)s_%(column_0_name)s_fkey",
    "pk": "%(table_name)s_pkey",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        onupdate=func.now(),
    )
