"""add signer evidence

Revision ID: 320b75a9eff9
Revises: 952beacf6c0f
Create Date: 2026-09-20 19:01:34.087613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '320b75a9eff9'
down_revision: Union[str, Sequence[str], None] = '952beacf6c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signer_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('signer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_event_id', sa.String(), nullable=True),
    sa.Column('identity_check_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_hash_at_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('signer_evidence_agreement_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signer_id'], ['external_parties.id'], name=op.f('signer_evidence_signer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('signer_evidence_pkey'))
    )
    op.create_index(op.f('ix_signer_evidence_agreement_id'), 'signer_evidence', ['agreement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signer_evidence_agreement_id'), table_name='signer_evidence')
    op.drop_table('signer_evidence')
    # ### end Alembic commands ###
