"""add_templates

Revision ID: 3374fdfaa40d
Revises: d0e1f2a3b4c5
Create Date: 2026-09-15 01:46:18.341467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3374fdfaa40d'
down_revision: Union[str, Sequence[str], None] = 'd0e1f2a3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('organization_id', sa.UUID(), nullable=True, comment='NULL means system-wide template (available to all tenants).'),
    sa.Column('agreement_type_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_type_id'], ['agreement_types.id'], name=op.f('templates_agreement_type_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('templates_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('templates_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('templates_pkey'))
    )
    op.create_index(op.f('ix_templates_agreement_type_id'), 'templates', ['agreement_type_id'], unique=False)
    op.create_index(op.f('ix_templates_organization_id'), 'templates', ['organization_id'], unique=False)
    op.create_table('template_variables',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('var_type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('template_variables_template_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('template_variables_pkey'))
    )
    op.create_index(op.f('ix_template_variables_template_id'), 'template_variables', ['template_id'], unique=False)
    op.create_table('template_versions',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('variables_snapshot', sa.JSON(), nullable=True),
    sa.Column('clauses_snapshot', sa.JSON(), nullable=True),
    sa.Column('rules_snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('template_versions_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('template_versions_template_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('template_versions_pkey')),
    sa.UniqueConstraint('template_id', 'version_number', name='template_versions_template_id_version_number_key')
    )
    op.create_index(op.f('ix_template_versions_template_id'), 'template_versions', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_versions_template_id'), table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_index(op.f('ix_template_variables_template_id'), table_name='template_variables')
    op.drop_table('template_variables')
    op.drop_index(op.f('ix_templates_organization_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_agreement_type_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
