"""close model drift: signature events, kyc session fields, orch constraints, monitoring indexes

Revision ID: 6c8d8f12370c
Revises: d3e0a1b2c3d4
Create Date: 2026-09-25 14:29:41.537059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8d8f12370c'
down_revision: Union[str, Sequence[str], None] = 'd3e0a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_party_signature_events',
    sa.Column('external_party_id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('authentication_method', sa.String(length=50), nullable=True),
    sa.Column('document_hash', sa.String(length=128), nullable=True),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('external_party_signature_events_agreement_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['external_party_id'], ['external_parties.id'], name=op.f('external_party_signature_events_external_party_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('external_party_signature_events_pkey'))
    )
    op.create_index(op.f('ix_external_party_signature_events_agreement_id'), 'external_party_signature_events', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_external_party_signature_events_external_party_id'), 'external_party_signature_events', ['external_party_id'], unique=False)
    op.add_column('external_parties', sa.Column('kyc_session_auth_method', sa.String(length=50), nullable=True))
    op.add_column('external_party_sessions', sa.Column('user_session_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_external_party_sessions_user_session_id'), 'external_party_sessions', ['user_session_id'], unique=False)
    op.create_index(op.f('ix_monitoring_evaluations_source_version_id'), 'monitoring_evaluations', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_monitoring_evidence_source_version_id'), 'monitoring_evidence', ['source_version_id'], unique=False)
    op.drop_constraint(op.f('orch_workflow_definitions_orch_workflow_definitions_sco_2a4b'), 'orch_workflow_definitions', type_='check')
    op.drop_constraint(op.f('orch_workflow_definitions_orch_workflow_definitions_sta_b2c4'), 'orch_workflow_definitions', type_='check')
    op.create_check_constraint(op.f('orch_workflow_definitions_scope_check'), 'orch_workflow_definitions', "scope IN ('global', 'organization', 'agreement_type')")
    op.create_check_constraint(op.f('orch_workflow_definitions_status_check'), 'orch_workflow_definitions', "status IN ('draft', 'active', 'disabled', 'archived')")
    op.drop_constraint(op.f('orch_workflow_instances_orch_workflow_instances_status__207a'), 'orch_workflow_instances', type_='check')
    op.create_check_constraint(op.f('orch_workflow_instances_status_check'), 'orch_workflow_instances', "status IN ('running', 'waiting', 'completed', 'failed', 'cancelled', 'suspended', 'human_intervention_required')")
    op.drop_constraint(op.f('orch_workflow_step_definitions_orch_workflow_step_defin_2a7e'), 'orch_workflow_step_definitions', type_='check')
    op.create_check_constraint(op.f('orch_workflow_step_definitions_step_type_check'), 'orch_workflow_step_definitions', "step_type IN ('task', 'approval', 'condition', 'delay', 'event_wait', 'action', 'parallel', 'subworkflow')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orch_workflow_step_definitions_step_type_check'), 'orch_workflow_step_definitions', type_='check')
    op.create_check_constraint(op.f('orch_workflow_step_definitions_orch_workflow_step_defin_2a7e'), 'orch_workflow_step_definitions', "step_type::text = ANY (ARRAY['task'::character varying, 'approval'::character varying, 'condition'::character varying, 'delay'::character varying, 'event_wait'::character varying, 'action'::character varying, 'parallel'::character varying, 'subworkflow'::character varying]::text[])")
    op.drop_constraint(op.f('orch_workflow_instances_status_check'), 'orch_workflow_instances', type_='check')
    op.create_check_constraint(op.f('orch_workflow_instances_orch_workflow_instances_status__207a'), 'orch_workflow_instances', "status::text = ANY (ARRAY['running'::character varying, 'waiting'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying, 'suspended'::character varying, 'human_intervention_required'::character varying]::text[])")
    op.drop_constraint(op.f('orch_workflow_definitions_status_check'), 'orch_workflow_definitions', type_='check')
    op.drop_constraint(op.f('orch_workflow_definitions_scope_check'), 'orch_workflow_definitions', type_='check')
    op.create_check_constraint(op.f('orch_workflow_definitions_orch_workflow_definitions_sta_b2c4'), 'orch_workflow_definitions', "status::text = ANY (ARRAY['draft'::character varying, 'active'::character varying, 'disabled'::character varying, 'archived'::character varying]::text[])")
    op.create_check_constraint(op.f('orch_workflow_definitions_orch_workflow_definitions_sco_2a4b'), 'orch_workflow_definitions', "scope::text = ANY (ARRAY['global'::character varying, 'organization'::character varying, 'agreement_type'::character varying]::text[])")
    op.drop_index(op.f('ix_monitoring_evidence_source_version_id'), table_name='monitoring_evidence')
    op.drop_index(op.f('ix_monitoring_evaluations_source_version_id'), table_name='monitoring_evaluations')
    op.drop_index(op.f('ix_external_party_sessions_user_session_id'), table_name='external_party_sessions')
    op.drop_column('external_party_sessions', 'user_session_id')
    op.drop_column('external_parties', 'kyc_session_auth_method')
    op.drop_index(op.f('ix_external_party_signature_events_external_party_id'), table_name='external_party_signature_events')
    op.drop_index(op.f('ix_external_party_signature_events_agreement_id'), table_name='external_party_signature_events')
    op.drop_table('external_party_signature_events')
    # ### end Alembic commands ###
