"""your message here

Revision ID: 8421f73f77d9
Revises: e6f7a8b9c0d1
Create Date: 2026-09-08 15:24:16.356175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8421f73f77d9'
down_revision: Union[str, Sequence[str], None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('idempotency_keys',
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('incoming_webhook_events',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_incoming_webhook_provider_event')
    )
    op.create_index(op.f('ix_incoming_webhook_events_provider'), 'incoming_webhook_events', ['provider'], unique=False)
    op.create_table('organization_holidays',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'holiday_date', name='uq_organization_holiday_date')
    )
    op.create_index(op.f('ix_organization_holidays_organization_id'), 'organization_holidays', ['organization_id'], unique=False)
    op.create_table('user_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('push_token', sa.String(length=1024), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_devices_user_device')
    )
    op.create_index(op.f('ix_user_devices_device_id'), 'user_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=True),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_quarantined', sa.Boolean(), nullable=False),
    sa.Column('quarantine_reason', sa.Text(), nullable=True),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quarantined_by', sa.UUID(), nullable=True),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disposed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quarantined_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_agreement_id'), 'documents', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_documents_is_quarantined'), 'documents', ['is_quarantined'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_table('document_relationships',
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('target_document_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obligation_assignees',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('agreement_party_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('responsibility_type', sa.String(length=100), nullable=False),
    sa.Column('primary_assignee', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_party_id'], ['agreement_parties.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obligation_assignees_member', 'obligation_assignees', ['member_id'], unique=False)
    op.create_index(op.f('ix_obligation_assignees_obligation_id'), 'obligation_assignees', ['obligation_id'], unique=False)
    op.create_table('obligation_deadlines',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('deadline_type', sa.String(length=100), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculation_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_event', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obligation_deadlines_due', 'obligation_deadlines', ['due_at'], unique=False)
    op.create_index(op.f('ix_obligation_deadlines_obligation_id'), 'obligation_deadlines', ['obligation_id'], unique=False)
    op.create_table('obligation_events',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('previous_status', sa.String(length=100), nullable=True),
    sa.Column('new_status', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obligation_events_created', 'obligation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_obligation_events_obligation_id'), 'obligation_events', ['obligation_id'], unique=False)
    op.create_table('obligation_evidence',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligation_evidence_obligation_id'), 'obligation_evidence', ['obligation_id'], unique=False)
    op.create_index('ix_obligation_evidence_status', 'obligation_evidence', ['status'], unique=False)
    op.create_table('obligation_recurrences',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('next_run_at', sa.Date(), nullable=False),
    sa.Column('occurrences_generated', sa.Integer(), nullable=False),
    sa.Column('max_occurrences', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obligation_recurrences_due', 'obligation_recurrences', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_obligation_recurrences_obligation_id'), 'obligation_recurrences', ['obligation_id'], unique=False)
    op.create_table('signing_sessions',
    sa.Column('signature_request_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=True),
    sa.Column('token_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['signature_request_id'], ['signature_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_signing_sessions_signature_request_id'), 'signing_sessions', ['signature_request_id'], unique=True)
    op.create_table('signature_placements',
    sa.Column('signing_session_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('field_key', sa.String(length=255), nullable=False),
    sa.Column('signature_type', sa.String(length=30), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['signing_session_id'], ['signing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signature_placements_signing_session_id'), 'signature_placements', ['signing_session_id'], unique=False)
    op.create_table('signing_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signing_session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('event_hash', sa.String(length=128), nullable=False),
    sa.Column('prev_event_hash', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signing_session_id'], ['signing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signing_session_id', 'event_hash', name='uq_signing_event_hash')
    )
    op.create_index(op.f('ix_signing_events_signing_session_id'), 'signing_events', ['signing_session_id'], unique=False)
    op.add_column('agreement_changes', sa.Column('proposing_party_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_agreement_changes_proposing_party_id'), 'agreement_changes', ['proposing_party_id'], unique=False)
    op.create_foreign_key('agreement_changes_proposing_party_id_fkey', 'agreement_changes', 'agreement_parties', ['proposing_party_id'], ['id'], ondelete='SET NULL')
    op.add_column('agreements', sa.Column('agreement_type_version', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_agreements_agreement_type_id'), 'agreements', ['agreement_type_id'], unique=False)
    op.add_column('approval_records', sa.Column('agreement_version_id', sa.UUID(), nullable=True))
    op.add_column('approval_records', sa.Column('approval_type', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_approval_records_agreement_version_id'), 'approval_records', ['agreement_version_id'], unique=False)
    op.create_foreign_key('approval_records_agreement_version_id_fkey', 'approval_records', 'agreement_versions', ['agreement_version_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('audit_chain_roots_tenant_id_key'), 'audit_chain_roots', type_='unique')
    op.drop_index(op.f('ix_audit_chain_roots_tenant_id'), table_name='audit_chain_roots')
    op.create_index(op.f('ix_audit_chain_roots_tenant_id'), 'audit_chain_roots', ['tenant_id'], unique=True)
    op.alter_column('audit_evidence', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(op.f('audit_evidence_created_by_fkey'), 'audit_evidence', type_='foreignkey')
    op.create_foreign_key('audit_evidence_created_by_fkey', 'audit_evidence', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('billing_plans_code_key'), 'billing_plans', type_='unique')
    op.create_index(op.f('ix_billing_plans_code'), 'billing_plans', ['code'], unique=True)
    op.alter_column('clause_library', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key('clause_library_published_by_fkey', 'clause_library', 'users', ['published_by'], ['id'])
    op.alter_column('erasure_requests', 'shredded_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('external_parties', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('field_encryption_records', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ingestion_jobs', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('integration_connectors', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('integration_connectors', 'events',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('integration_connectors', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('knowledge_chunks', 'embedding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledge_chunks', 'party_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledge_chunks', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_knowledge_chunks_clause_id'), 'knowledge_chunks', ['clause_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_jurisdiction'), 'knowledge_chunks', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_version_id'), 'knowledge_chunks', ['version_id'], unique=False)
    op.add_column('obligations', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('obligations', sa.Column('source_clause_id', sa.UUID(), nullable=True))
    op.add_column('obligations', sa.Column('source_document_id', sa.UUID(), nullable=True))
    op.add_column('obligations', sa.Column('source_version_id', sa.UUID(), nullable=True))
    op.add_column('obligations', sa.Column('source_text', sa.Text(), nullable=True))
    op.add_column('obligations', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('obligations', sa.Column('criticality', sa.String(length=30), nullable=False))
    op.add_column('obligations', sa.Column('evidence_status', sa.String(length=30), nullable=False))
    op.add_column('obligations', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('obligations', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_index('ix_obligations_agreement_status', 'obligations', ['agreement_id', 'status'], unique=False)
    op.create_index(op.f('ix_obligations_organization_id'), 'obligations', ['organization_id'], unique=False)
    op.create_foreign_key('obligations_organization_id_fkey', 'obligations', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('obligations_source_document_id_fkey', 'obligations', 'documents', ['source_document_id'], ['id'])
    op.create_foreign_key('obligations_created_by_fkey', 'obligations', 'users', ['created_by'], ['id'])
    op.alter_column('ocr_documents', 'extracted_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('outbox_events', sa.Column('actor_user_id', sa.UUID(), nullable=True))
    op.add_column('outbox_events', sa.Column('event_version', sa.Integer(), nullable=False))
    op.add_column('outbox_events', sa.Column('available_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbox_events', sa.Column('event_key', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_outbox_events_event_key'), 'outbox_events', ['event_key'], unique=False)
    op.create_unique_constraint('uq_outbox_events_event_key', 'outbox_events', ['event_key'])
    op.create_foreign_key('outbox_events_actor_user_id_fkey', 'outbox_events', 'users', ['actor_user_id'], ['id'])
    op.alter_column('redaction_requests', 'targets',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.alter_column('repository_records', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('retention_records', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_retention_records_agreement'), 'retention_records', type_='unique')
    op.create_index(op.f('ix_retention_records_agreement_id'), 'retention_records', ['agreement_id'], unique=True)
    op.alter_column('risk_graph_edges', 'properties',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('risk_graph_nodes', 'properties',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('signature_requests', sa.Column('signing_order', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('subscriptions_tenant_id_key'), 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=True)
    op.alter_column('user_activity', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_activity', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_unique_constraint(op.f('subscriptions_tenant_id_key'), 'subscriptions', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('signature_requests', 'signing_order')
    op.alter_column('risk_graph_nodes', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('risk_graph_edges', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_retention_records_agreement_id'), table_name='retention_records')
    op.create_unique_constraint(op.f('uq_retention_records_agreement'), 'retention_records', ['agreement_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('retention_records', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('repository_records', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('redaction_requests', 'targets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('outbox_events_actor_user_id_fkey', 'outbox_events', type_='foreignkey')
    op.drop_constraint('uq_outbox_events_event_key', 'outbox_events', type_='unique')
    op.drop_index(op.f('ix_outbox_events_event_key'), table_name='outbox_events')
    op.drop_column('outbox_events', 'event_key')
    op.drop_column('outbox_events', 'available_at')
    op.drop_column('outbox_events', 'event_version')
    op.drop_column('outbox_events', 'actor_user_id')
    op.alter_column('ocr_documents', 'extracted_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('obligations_created_by_fkey', 'obligations', type_='foreignkey')
    op.drop_constraint('obligations_source_document_id_fkey', 'obligations', type_='foreignkey')
    op.drop_constraint('obligations_organization_id_fkey', 'obligations', type_='foreignkey')
    op.drop_index(op.f('ix_obligations_organization_id'), table_name='obligations')
    op.drop_index('ix_obligations_agreement_status', table_name='obligations')
    op.drop_column('obligations', 'created_by')
    op.drop_column('obligations', 'metadata_json')
    op.drop_column('obligations', 'evidence_status')
    op.drop_column('obligations', 'criticality')
    op.drop_column('obligations', 'title')
    op.drop_column('obligations', 'source_text')
    op.drop_column('obligations', 'source_version_id')
    op.drop_column('obligations', 'source_document_id')
    op.drop_column('obligations', 'source_clause_id')
    op.drop_column('obligations', 'organization_id')
    op.drop_index(op.f('ix_knowledge_chunks_version_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_jurisdiction'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_clause_id'), table_name='knowledge_chunks')
    op.alter_column('knowledge_chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledge_chunks', 'party_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledge_chunks', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('integration_connectors', 'last_sync_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('integration_connectors', 'events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('integration_connectors', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ingestion_jobs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('field_encryption_records', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('external_parties', 'expires_at')
    op.alter_column('erasure_requests', 'shredded_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('clause_library_published_by_fkey', 'clause_library', type_='foreignkey')
    op.alter_column('clause_library', 'published_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_billing_plans_code'), table_name='billing_plans')
    op.create_unique_constraint(op.f('billing_plans_code_key'), 'billing_plans', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('audit_evidence_created_by_fkey', 'audit_evidence', type_='foreignkey')
    op.create_foreign_key(op.f('audit_evidence_created_by_fkey'), 'audit_evidence', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('audit_evidence', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_chain_roots_tenant_id'), table_name='audit_chain_roots')
    op.create_index(op.f('ix_audit_chain_roots_tenant_id'), 'audit_chain_roots', ['tenant_id'], unique=False)
    op.create_unique_constraint(op.f('audit_chain_roots_tenant_id_key'), 'audit_chain_roots', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('approval_records_agreement_version_id_fkey', 'approval_records', type_='foreignkey')
    op.drop_index(op.f('ix_approval_records_agreement_version_id'), table_name='approval_records')
    op.drop_column('approval_records', 'approval_type')
    op.drop_column('approval_records', 'agreement_version_id')
    op.drop_index(op.f('ix_agreements_agreement_type_id'), table_name='agreements')
    op.drop_column('agreements', 'agreement_type_version')
    op.drop_constraint('agreement_changes_proposing_party_id_fkey', 'agreement_changes', type_='foreignkey')
    op.drop_index(op.f('ix_agreement_changes_proposing_party_id'), table_name='agreement_changes')
    op.drop_column('agreement_changes', 'proposing_party_id')
    op.drop_index(op.f('ix_signing_events_signing_session_id'), table_name='signing_events')
    op.drop_table('signing_events')
    op.drop_index(op.f('ix_signature_placements_signing_session_id'), table_name='signature_placements')
    op.drop_table('signature_placements')
    op.drop_index(op.f('ix_signing_sessions_signature_request_id'), table_name='signing_sessions')
    op.drop_table('signing_sessions')
    op.drop_index(op.f('ix_obligation_recurrences_obligation_id'), table_name='obligation_recurrences')
    op.drop_index('ix_obligation_recurrences_due', table_name='obligation_recurrences')
    op.drop_table('obligation_recurrences')
    op.drop_index('ix_obligation_evidence_status', table_name='obligation_evidence')
    op.drop_index(op.f('ix_obligation_evidence_obligation_id'), table_name='obligation_evidence')
    op.drop_table('obligation_evidence')
    op.drop_index(op.f('ix_obligation_events_obligation_id'), table_name='obligation_events')
    op.drop_index('ix_obligation_events_created', table_name='obligation_events')
    op.drop_table('obligation_events')
    op.drop_index(op.f('ix_obligation_deadlines_obligation_id'), table_name='obligation_deadlines')
    op.drop_index('ix_obligation_deadlines_due', table_name='obligation_deadlines')
    op.drop_table('obligation_deadlines')
    op.drop_index(op.f('ix_obligation_assignees_obligation_id'), table_name='obligation_assignees')
    op.drop_index('ix_obligation_assignees_member', table_name='obligation_assignees')
    op.drop_table('obligation_assignees')
    op.drop_table('document_relationships')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_quarantined'), table_name='documents')
    op.drop_index(op.f('ix_documents_agreement_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_organization_holidays_organization_id'), table_name='organization_holidays')
    op.drop_table('organization_holidays')
    op.drop_index(op.f('ix_incoming_webhook_events_provider'), table_name='incoming_webhook_events')
    op.drop_table('incoming_webhook_events')
    op.drop_table('idempotency_keys')
    op.drop_table('document_types')
    # ### end Alembic commands ###
