"""Add special form record

Revision ID: 89f1bb6ef3b2
Revises: 320b75a9eff9
Create Date: 2026-09-20 19:05:01.671179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f1bb6ef3b2'
down_revision: Union[str, Sequence[str], None] = '320b75a9eff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_form_records',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('notary_or_witness_name', sa.String(length=255), nullable=True),
    sa.Column('notarization_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_scan_key', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('special_form_records_agreement_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('special_form_records_pkey'))
    )
    op.create_index(op.f('ix_special_form_records_agreement_id'), 'special_form_records', ['agreement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_special_form_records_agreement_id'), table_name='special_form_records')
    op.drop_table('special_form_records')
    # ### end Alembic commands ###
