"""Add sealed_document_key to Agreement

Revision ID: 952beacf6c0f
Revises: a5a2636cf09d
Create Date: 2026-09-20 18:54:58.426209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952beacf6c0f'
down_revision: Union[str, Sequence[str], None] = 'a5a2636cf09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('sealed_document_key', sa.String(), nullable=True))
    op.add_column('agreements', sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements', 'sealed_at')
    op.drop_column('agreements', 'sealed_document_key')
    # ### end Alembic commands ###
