"""add_stored_objects

Revision ID: a5a2636cf09d
Revises: f8b9c0d1e2f3
Create Date: 2026-09-20 18:51:54.638108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a2636cf09d'
down_revision: Union[str, Sequence[str], None] = 'f8b9c0d1e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_objects',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('sha256_hash', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('backend', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name=op.f('stored_objects_agreement_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('stored_objects_uploaded_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('stored_objects_pkey'))
    )
    op.create_index(op.f('ix_stored_objects_agreement_id'), 'stored_objects', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_stored_objects_key'), 'stored_objects', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stored_objects_key'), table_name='stored_objects')
    op.drop_index(op.f('ix_stored_objects_agreement_id'), table_name='stored_objects')
    op.drop_table('stored_objects')
    # ### end Alembic commands ###
